services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=gorm_learning
      - PORT=3000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    # image: mysql:8.0  # (~764MB on macOS - ~1GB on Windows image)
    # image: mysql:8.0-oraclelinux9 # Also 1.04GB on Windows, same as the debian based "mysql:8.0" image
    # image: mysql/mysql-server:8.0 # failed, no permission
    image: mariadb:10.6 # 539MB on Windows
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: gorm_learning
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -uroot -p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 30s
    networks:
      - app-network

  phpmyadmin:
    # image: phpmyadmin/phpmyadmin  # (~570MB on macOS - ~814MB on Windows image)
    image: adminer  # Image size is 171.3MB on Windows
    restart: always
    ports:
      # - "8080:80" # "HOST_PORT:CONTAINER_PORT" (since phpmyadmin/phpmyadmin listens for internal port of 80)
      - "8080:8080"  # "HOST_PORT:CONTAINER_PORT" (since adminer listens for internal port of 8080)
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=rootpassword
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
